# Generated by Django 2.2.4 on 2019-11-01 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('question_Explain', models.CharField(max_length=400)),
                ('person', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='comment_for_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.CharField(max_length=90000)),
                ('comment_user', models.CharField(blank=True, max_length=50)),
                ('comment_for_project_name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Computer_Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_user', models.CharField(blank=True, max_length=60)),
                ('notification_link', models.CharField(max_length=300)),
                ('notification_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(max_length=20)),
                ('subsemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=60)),
                ('usub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='semcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.Study'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_image', models.ImageField(blank=True, upload_to='project_images')),
                ('project_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.Project_Language')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(blank=True, max_length=12)),
                ('age', models.CharField(blank=True, max_length=12)),
                ('bio', models.CharField(blank=True, max_length=150)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('user_image', models.ImageField(blank=True, default='Userpics/none/face-1.jpg', upload_to='Userpics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('files', models.FileField(upload_to='')),
                ('img1', models.ImageField(upload_to='images')),
                ('subfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Computer_Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=150)),
                ('program_file', models.FileField(blank=True, upload_to='Program')),
                ('programlanguage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.Computer_Language')),
            ],
        ),
    ]
