# Generated by Django 2.2.4 on 2019-11-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer_language',
            old_name='lname',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='computer_program',
            old_name='pname',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='computer_program',
            old_name='program_file',
            new_name='program_files',
        ),
        migrations.RenameField(
            model_name='computer_program',
            old_name='programlanguage',
            new_name='program_language',
        ),
    ]
