# Generated by Django 2.2.4 on 2019-11-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_auto_20191102_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_File',
            field=models.FileField(blank=True, upload_to='project_files'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_output_1',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_output_2',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
    ]
