# Generated by Django 2.2.4 on 2019-11-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_project_project_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_bio',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
